### ISSUE TITLE
源码运行好像也有问题

### ISSUE THREAD

**Issue by yansheng836** [SnailMann/CAB-Tool#4]
配置后运行出错了，保存如下

```bash
λ py main.py
==================================================begin====================================================
Backup Path : D:\csdn-blog-backup
Download Picture Or Not ?  False
Crawl article interval : 1 seconds
===========================================================================================================
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    _main()
  File "main.py", line 41, in _main
    user = login.dologin(GLO_CONFIG['username'], GLO_CONFIG['password'])
  File "G:\Git\git_repository\CAB-Tool\src\login.py", line 47, in dologin
    raise Exception(res.text)
Exception: {"msg":"页面过期","code":"1015","message":"系统繁忙，请稍候再试","status":false}
```

我找到了该行

```python
# login error
        if not res.status_code == 200:
            raise Exception(res.text)
```

个人猜想：记得之前csdn对密码要求有点高，然后密码中加了个特殊符号 `@` ，不知道是不是因为这个原因？

但是看报错好像是状态码的问题，想问下“登录失败”有进行处理吗？

**Comment by yansheng836** [comment]
我打印了下状态码，发现是400，查了下解释为： (错误请求) 服务器不理解请求的语法，是否是登录失败的原因？

**Comment by SnailMann** [comment]
@yansheng836 yansheng836 这是因为几个月前，CSDN引入了阿里的反爬机制，导致目前的login模块失效了。暂时没有分析出个所以然。你可以分析挑战一下。当然登录机制也不是必要的，可以使用临时解决方案，从浏览器copy cookies下来，使用main_cookie.py去跑就行了

**Comment by yansheng836** [comment]
原来如此，最近CSDN是变了挺多的呢。
